### ISSUE TITLE
[Compatibility] With extra-sounds mod

### ISSUE THREAD

**Issue by Aces-and-Jacks** [wisp-forest/CondensedCreativeItems#3] opened 2022-11-13 08:14 UTC
When I enable this mod it causes some sounds from extra-sounds mod to not work

**Comment by Aces-and-Jacks** [comment] 2022-12-08 00:15
https://github.com/stashymane/extra-sounds/issues/88

**Comment by Aces-and-Jacks** [comment] 2023-01-03 03:05
um...is this possible or would extra sounds need to do something on their end

**Comment by Dragon-Seeker** [comment] 2023-01-03 22:58
Sorry for not getting back to you, the issue is that I do a lot of replacement in a sense for the backend of the Creative Inventory so I would need to see about adding compat or look into if I can fix such somehow

**Comment by Dragon-Seeker** [comment] 2024-04-17 00:35
I am closing this as I do not have the time to investigate such a feature at the moment and expect support on the side of the other mod going forward if anything is to be done.

**Closed as completed by Dragon-Seeker** 2024-04-17 00:35 UTC
